export const FETCH_SEARCH_REQUEST = "FETCH_SEARCH_REQUEST";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const EMPTY_SEARCH = "EMPTY_SEARCH";
